### ISSUE TITLE
Can't open the preferences tab.

### ISSUE THREAD

**Issue by DaviRaubach** [karimhaddad/omlily3#1]
Hi, I can compile .ly files in both examples, lilypond is running in the command line,  but, can't open the preferences tab. 

I get the following error: 

```
====================
 OpenMusic v. 6.16.0.0                            
 r. 2020/01/13
 (c) IRCAM - Representations Musicales
 http://repmus.ircam.fr/openmusic/
 ====================

Loading workspace: 'omlily 3.1' ...
Workspace loaded
Loading patch: /Users/Davi/OM/Libraries/omlily 3.1/elements/ex-1.omp
OM > "Loading library omlily - v. 3.1"

Warning : Either Lilypond is not installed or you didn't installed
        or 
        It is no where to be used in command line.
      Please follow these instruction in order to make the library work :
     http://www.lilypond.org/macos-x.html
OM > "ERROR: Illegal use of a pathname host in #P"Warning : Either Lilypond is not installed or you didn't installed
        or 
        It is no where to be used in command line.
      Please follow these instruction in order to make the library work :/
     http:/www.lilypond.org/macos-x.html".

Call to om-lisp::om-error-handler
Call to invoke-debugger
Call to error
Call to probe-file
Call to (method make-new-pref-scroll ((eql :externals) t))
Call to make-preference-win
Call to omg-make-preference-dialog
Call to capi::internal-funcall-using-callback-type
Call to capi::execute-callback
Call to capi::execute-callback-1
Call to capi:execute-with-interface
Call to (subfunction capi-cocoa-library::|%FOREIGN-CALLABLE/CAPI_COCOA_LIBRARY MENU_REPRESENTATION ObjC instance method _CAPIMenuItemSelected:| (fli:define-foreign-callable "CAPI_COCOA_LIBRARY MENU_REPRESENTATION ObjC instance method _CAPIMenuItemSelected:"))
Call to objc::|invoke (FUNCTION (OBJC-OBJECT-POINTER SEL) VOID)|
Call to (subfunction 2 objc::make-invoke-function)
Call to objc::invoke-into*
Call to capi-cocoa-library::run-cocoa-event-loop
Call to mp::process-sg-function
Call to mp::run-main-process-once
Call to mp::multiprocessing-main-loop
Call to mp::shared-initialize-multiprocessing
Call to mp:initialize-multiprocessing
"
OM > "macos-x"
OM => #P"/Users/Davi/Desktop/Untitled.pdf"
```

OSX 10.13.6
Lilypond 2.21.0
OM 6.16

Thanks

**Comment by karimhaddad** [comment]
Hi Davi, 

Just a question:
Did you install lilypond , (which version), and did you follow the instructions on this page (right column):
   
http:/www.lilypond.org/macos-x.html

This should make available the usage of Lilypond through the command line (Terminal), which is mandatory to have the compilation of the .ly file automaticaly by omlily lib.
If not, you should have already have a .ly file that you can compile using the .app
However, it is more interesting to have this fixed.

Soon i will provide a more robust fix for this issue.

Best
K

**Comment by DaviRaubach** [comment]
Hi,
Thank you for the quick reply. 

I'm using Lilypond version 2.21.0 (OSX 10.13.6 and OpenMusic 6.16).
Yes, I did what is on that page. I can run lilypond through the command line, compile and generate the pdf. 
Yes, generating the .ly file is good enough. It's just bad the error when I try to access the preferences. 
I think it's a problem of paths... Is there any place in the .lisp files where I can put the direct path to my lilypond?
Let me know if I can give you some other information.

Best, 
Davi

**Comment by karimhaddad** [comment]
Hi, 

Sorry, just to be sure about your problem. You cannot at all access the OM preferences panel  or specifically the lilypond tab preference panel ?

**Comment by karimhaddad** [comment]
Dear Davi 

Ok my bad... I understand the problem now. Your script (lilypond) used to launch lilypond from Terminal is not in a path known by your terminal. Although if not in the path, you are right, this shouldn't happen, ie blocking the preferences panel.
what you should do is to put the script in a path known to your environment. Usually i create in my Users/home a folder called "bin: (as binary). I put the script there. Then and most important is to add this in your ".bash_profile" file which is a hidden file in your User's home:
PATH=$PATH:~/bin
export PATH

that way you can call the script wherever you are located.
This is what should be. However i will fix this bug ASAP..
Thanx for reporting it.

Best
K

**Comment by DaviRaubach** [comment]
> Hi,
> 
> Sorry, just to be sure about your problem. You cannot at all access the OM preferences panel or specifically the lilypond tab preference panel ?

The OM preferences, at all. 

Ah, the problem was that I had the path in ".profile" and not in ".bash_profile". That is because in the [lilypond page](http://lilypond.org/doc/v2.19/Documentation/web/macos-x) it says ".profile"... 
Now I put it in ".bash_profile" and it is running perfectly.
Thank you,
Davi
